"""Cycles pédagogiques officiels 2026-2027 issus des documents fournis par l'utilisateur.

Chaque entrée décrit une séance structurée et les codes de compétences de l'APK
à lui associer. Les contenus restent volontairement proches des documents source.
"""

SSA_COMPETENCIES = (
    ("SSA1", "Situer son rôle et sa mission"),
    ("SSA2", "Analyser les risques"),
    ("SSA3", "Développer des actions de prévention"),
    ("SSA4", "Participer à un dispositif de surveillance"),
    ("SSA5", "Participer à une action coordonnée de sauvetage"),
)


def _s(activity, n, title, objective, competencies, situations, *,
       material=(), warmup="", criteria=(), safety=(), bilan="", description=""):
    return {
        "activity": activity,
        "number": n,
        "title": f"Séance {n} — {title}",
        "objective": objective,
        "competencies": list(competencies),
        "situations": list(situations),
        "material": list(material),
        "warmup": warmup,
        "criteria": list(criteria),
        "safety": list(safety),
        "bilan": bilan,
        "description": description or objective,
    }


CYCLE_SESSION_SEEDS = []

# ---------------------------------------------------------------------------
# Course à pied — VMA / endurance — 8 séances
# ---------------------------------------------------------------------------
course_common = (
    "Accueil / objectif 5 min ; échauffement 12-15 min ; technique 8-10 min ; "
    "travail principal 25-30 min ; tonicité/gainage 10-12 min ; retour au calme 5 min."
)
CYCLE_SESSION_SEEDS += [
    _s("Course à pied", 1, "45 secondes : « Je cours vite mais relâché »",
       "Développer VMA, tonicité et qualité des appuis.",
       ["CAP1", "CAP3", "CAP4"],
       ["2 × 8 × 45 s / 45 s à 95-100 % VMA.", "Travail de fréquence, appuis et tonicité.", "Fin : squats, fentes, mollets, gainage."],
       warmup=course_common, criteria=["Maintenir une vitesse rapide mais relâchée sur les répétitions."],
       safety=["Échauffement progressif avant les intensités élevées."],
       bilan="Ressenti, allure et réussite du contrat."),
    _s("Course à pied", 2, "1 min 30 : « Je maintiens ma vitesse »",
       "Maintenir une allure rapide sur des fractions plus longues.",
       ["CAP1", "CAP2", "CAP3"],
       ["2 × 5 × 1 min 30 à 90-95 % VMA.", "Récupération 1 min ; 3 min entre séries.", "Chercher une distance stable à chaque répétition."],
       warmup=course_common, criteria=["Limiter la dérive de distance entre la première et la dernière répétition."],
       bilan="Comparer vitesse prévue, vitesse tenue et sensations."),
    _s("Course à pied", 3, "3 minutes : « Je trouve mon allure »",
       "Développer l'endurance à allure soutenue et apprendre à réguler.",
       ["CAP1", "CAP2", "CAP3"],
       ["5 × 3 min à 85-90 % VMA.", "Récupération 1 min 30.", "Relever les distances et limiter l'écart entre meilleure et moins bonne répétition."],
       warmup=course_common, criteria=["Distances proches d'une répétition à l'autre."],
       bilan="Identifier l'allure soutenable la plus régulière."),
    _s("Course à pied", 4, "6 minutes : « Je deviens régulier »",
       "Développer la régularité et la gestion d'allure.",
       ["CAP1", "CAP2", "CAP3"],
       ["3 × 6 min à 80-85 % VMA.", "Récupération 2 min.", "Réaliser trois distances proches ; dernière séquence éventuellement progressive."],
       warmup=course_common, criteria=["Maintenir une allure régulière sans départ excessif."],
       bilan="Analyser les écarts entre les trois blocs."),
    _s("Course à pied", 5, "12 minutes : « Je construis mon projet »",
       "Préparer le test 12 min et construire un projet d'allure.",
       ["CAP1", "CAP2", "CAP4"],
       ["2 × 12 min à 70-80 % VMA.", "Récupération 3 min.", "Premier 12 min contrôlé ; second avec objectif annoncé : distance, allure et stratégie."],
       warmup=course_common, criteria=["Objectif annoncé réaliste et stratégie cohérente."],
       bilan="Comparer projet annoncé et résultat."),
    _s("Course à pied", 6, "24 minutes : « Je sais gérer un effort long »",
       "Développer l'endurance longue et la stratégie.",
       ["CAP1", "CAP2", "CAP4"],
       ["24 min en continu à 65-75 % VMA.", "Relevés à 6, 12, 18 et 24 min.", "Analyser régularité et stratégie."],
       warmup=course_common, criteria=["Allure maîtrisée sur l'ensemble des 24 min."],
       bilan="Repérer les moments de dérive d'allure."),
    _s("Course à pied", 7, "Évaluation — Test 12 min",
       "Évaluer performance, projet et maîtrise de l'allure sur 12 minutes.",
       ["CAP1", "CAP2", "CAP3", "CAP4"],
       ["Annonce de la VMA, de la distance projetée, de l'allure et de la stratégie.", "Test 12 min.", "Relevés possibles à 3, 6, 9 et 12 min."],
       criteria=["Confronter projet et résultat ; observer régularité et efficacité de course."],
       bilan="Analyse du projet personnel et de la performance."),
    _s("Course à pied", 8, "Évaluation — Test 24 min",
       "Évaluer endurance, maîtrise et gestion de l'effort sur 24 minutes.",
       ["CAP1", "CAP2", "CAP3", "CAP4"],
       ["Annonce du projet personnel.", "Test 24 min.", "Relevés à 6, 12, 18 et 24 min."],
       criteria=["Régularité et gestion de l'effort particulièrement observées."],
       bilan="Bilan de progression et analyse de la stratégie."),
]

# ---------------------------------------------------------------------------
# Natation — 10 séances — 4 lignes de niveau
# ---------------------------------------------------------------------------
nat_mat = ("Planches", "Pull-buoys", "Chronomètres", "Matériel de renforcement")
nat_safe = ("Respecter le sens de circulation et les départs espacés.", "Adapter les départs et plongeons au niveau et à la profondeur.")
CYCLE_SESSION_SEEDS += [
    _s("Natation", 1, "Diagnostic, constitution des lignes et projet compétition",
       "Identifier le niveau, choisir une spécialité et entrer dans le projet collectif.",
       ["NAT1", "NAT2", "NAT3"],
       ["L1 : immersion, expiration, glissées, battements, 6-10×25 m ; objectif 25 m autonome.",
        "L2 : 200 m varié, 6×50 éducatif/nage complète, 4×50 crawl régulier ; test 50 m.",
        "L3 : 300 m, 6×50 technique, 4×100 progressifs + 4×25 rapide ; test 100 m.",
        "L4 : 400 m varié, 4×100 4N, 8×50, départs/coulées ; test 100 m + 50 m spécialité.",
        "Fin : relais découverte 4×25 ou 4×50 ; premiers chronos."],
       material=nat_mat, criteria=["Choisir une spécialité : papillon, dos, brasse, crawl ou 4N."], safety=nat_safe,
       bilan="Constitution des 4 lignes et premier temps de référence."),
    _s("Natation", 2, "Respiration, alignement, coulées et crawl",
       "Nager plus efficacement et mieux gérer l'effort.",
       ["NAT1", "NAT2", "NAT4"],
       ["L1 : expiration aquatique, inspiration latérale, 8×25 crawl adapté, glissées/battements.",
        "L2 : 8×25 respiration contrôlée, 6×50 rattrapé/crawl, 4×50 réguliers.",
        "L3 : 400 m + 8×50 éducatifs, 6×100 R20'', coulées/reprises.",
        "L4 : 400 m + 8×50 éducatifs, 8×100 réguliers, départ/coulée/reprise.",
        "Fin : relais 100 m à 2, temps total + 2 splits."],
       material=nat_mat, criteria=["Améliorer expiration, alignement et crawl économique."], safety=nat_safe,
       bilan="Comparer efficacité technique et gestion respiratoire."),
    _s("Natation", 3, "Technique des spécialités",
       "Construire une nage de spécialité efficace et l'associer au crawl.",
       ["NAT1", "NAT2", "NAT3"],
       ["L1 : crawl + dos, glissées, battements, bras, respiration.",
        "L2 : 8×25 éducatifs spécialité, 8×50 crawl/spécialité, 4×25 vite.",
        "L3 : 300 m + 4×50 spécialité, 8×75 (50 crawl +25 spécialité), 6×25 vite.",
        "L4 : 400 m + 8×50 éducatifs 4N, 8×100 crawl/spécialité, 8×25 vitesse.",
        "Fin : relais 100 m à 2 en pap/dos/brasse/crawl ; temps total + splits."],
       material=nat_mat, criteria=["Identifier deux points techniques personnels."], safety=nat_safe,
       bilan="Feedback technique par binômes."),
    _s("Natation", 4, "Parties non nagées : départs, virages, coulées, relais",
       "Gagner du temps sans nager plus vite.",
       ["NAT2", "NAT4"],
       ["Départs, coulées, reprises, virages, arrivées et prises de relais.",
        "L1 : départ bord/dans l'eau, coulée courte, virage simple, relais 4×25.",
        "L2 : 6 départs + 6 virages, 6×50 continuité, 4 prises de relais.",
        "L3 : 8 départs + 8 virages, 6×50, relais 50 m lancé.",
        "L4 : départs 15 m chronométrés, virages 5 m avant/après, relais lancés.",
        "Fin : répétition C1 8×50 avec couples P/D, D/B, B/NL, NL/P."],
       material=nat_mat, criteria=["Temps C1 total + split de chaque 50 m."], safety=nat_safe,
       bilan="Identifier la partie non nagée la plus coûteuse."),
    _s("Natation", 5, "Vitesse, fractionné et bloc C2",
       "Préparer les quatre relais 100 m à 2.",
       ["NAT2", "NAT3", "NAT4"],
       ["Travail vitesse 25/50 m et spécialité selon les 4 lignes.",
        "L3 : 12×50 1 modéré/1 rapide + 6×25 spécialité + 4×50 allure relais.",
        "L4 : 16×50 en 4 blocs + 8×25 départ lancé + 4×50 spécialité course.",
        "Fin : simulation C2 : 100 Pap, 100 Dos, 100 Brasse, 100 NL à 2 ; 2 splits par course."],
       material=nat_mat, criteria=["Stabiliser la spécialité et tester les binômes."], safety=nat_safe,
       bilan="Comparer les binômes et les temps intermédiaires."),
    _s("Natation", 6, "Spécifique compétition : C1 + C3",
       "Construire les équipes et tester les compositions.",
       ["NAT1", "NAT2", "NAT3", "NAT4"],
       ["Répéter le 400 m 4N à 8 et préparer le 8×100 NL.", "Travail de régularité et stratégie d'ordre de passage.",
        "C1 complet : temps total + 8 splits de 50 m.", "C3 : 8×100 NL, total + 8 splits de 100 m."],
       material=nat_mat, criteria=["Analyser les temps intermédiaires et optimiser la composition."], safety=nat_safe,
       bilan="Rôles chronométreurs et secrétariat."),
    _s("Natation", 7, "Endurance de relais et record de l'heure",
       "Répéter des 50 m réguliers et apprendre à gérer une équipe.",
       ["NAT1", "NAT2", "NAT3"],
       ["L1 : 16×25 puis 6-8×50 avec récupération complète.", "L2 : 12×50 réguliers + 4×50 technique.",
        "L3 : 16×50, écart cible <2-3 s + 4×100.", "L4 : 20×50, écart cible <2 s + 4×100.",
        "Mini-record de 20 min par équipes de 8 à 12, relais tous les 50 m."],
       material=nat_mat, criteria=["Temps de chaque 50 m, distance cumulée et passages toutes les 5 min."], safety=nat_safe,
       bilan="Rôles capitaine, compteur, chronométreur et saisie."),
    _s("Natation", 8, "Record de l'heure : stratégie et régularité",
       "Simuler 30 minutes et fixer l'allure cible.",
       ["NAT1", "NAT2", "NAT3"],
       ["Équipe cible de 12 nageurs, un seul nageur dans l'eau, relais tous les 50 m.",
        "Travail régulier adapté aux 4 lignes.", "Simulation record de l'heure sur 30 min.",
        "Suivi : distance totale, nombre de 50 m, moyenne au 50, passages 5/10/15/20/25/30 min."],
       material=nat_mat, criteria=["Tester l'ordre de passage et déterminer une allure soutenable."], safety=nat_safe,
       bilan="Analyser le tableau de suivi et ajuster la stratégie."),
    _s("Natation", 9, "Répétition générale de la rencontre",
       "Réaliser la compétition à blanc et répartir définitivement les rôles.",
       ["NAT1", "NAT2", "NAT3", "NAT4"],
       ["Échauffements adaptés aux 4 lignes.", "Programme blanc : C1 400 4N à 8 ; C2 4×100 à 2 ; C3 8×100 NL ; bonus 12×50 NL mixte.",
        "Chambre d'appel, starter, chronos, juges et saisie des résultats."],
       material=nat_mat, criteria=["Collecter tous les temps totaux et intermédiaires."], safety=nat_safe,
       bilan="Validation des compositions, départs, relais et rôles."),
    _s("Natation", 10, "Rencontre interuniversitaire Toulouse - UPPA - Bordeaux",
       "Réaliser la compétition par équipes sur 5 lignes d'eau.",
       ["NAT1", "NAT2", "NAT3", "NAT4"],
       ["Catégories masculin, féminin, mixte ; équipes de 8 à 9 nageurs.",
        "C1 : 8×50 couples de nages (coef 4).",
        "C2 : 100 Pap, Dos, Brasse, NL à 2 (coef 1 chacun, bloc coef 4).",
        "C3 : 8×100 NL (coef 6). Bonus : 12×50 NL mixte.",
        "Classement : RM / performance ×100 ; général=(C1×4+C2×4+C3×6)/14."],
       material=nat_mat, criteria=["Assurer une organisation fiable et collecter tous les splits."], safety=nat_safe,
       bilan="Les non-nageurs assurent les rôles officiels."),
]

# ---------------------------------------------------------------------------
# Rugby universitaire — 13 séances
# ---------------------------------------------------------------------------
rug_safe = ("Sécuriser toutes les situations de contact.", "Respecter les règles, les partenaires, adversaires et consignes.")
rug_sessions = [
(1,"Touch Rugby – entrée dans l'activité","Entrer dans l'activité, observer les niveaux et construire les premières continuités.",["RUG1","RUG2","RUG4"],
 ["Règles et sécurité ; échauffement avec ballon ; passes en mouvement.","Avancer / soutenir / transmettre ; 2c1, 3c2.","Matchs Touch à effectif réduit."]),
(2,"Contact / sécurité / PPI","Maîtriser les attitudes de contact en sécurité et développer la préparation physique intégrée.",["RUG3","RUG4"],
 ["Placement du corps, gainage, stabilité, chute et sécurité.","Travail au bouclier ; attitudes porteur/plaqueur.","PPI : jambes, poussées, tirages, appuis, gainage."]),
(3,"Qualité de passe","Améliorer précision, vitesse de transmission et replacement.",["RUG1","RUG2"],
 ["Passe des deux côtés, précision et communication.","2c1, 3c2, 4c3.","Match à thème favorisant la continuité."]),
(4,"Projet de jeu offensif + PPI – Synthétique Escudé","Construire le projet de jeu offensif.",["RUG1","RUG2","RUG4"],
 ["Fixer avant de transmettre ; soutien intérieur/extérieur.","Jeu dans l'axe et la largeur ; circulation offensive.","PPI : accélérations, changements de direction, répétition d'efforts."]),
(5,"Continuité / soutien / préparation tournoi","Maintenir la continuité et préparer collectivement le tournoi Touch.",["RUG1","RUG2","RUG4"],
 ["Conservation après contact, soutien au porteur et replacement.","Préparation collective au tournoi Touch Rugby."]),
(6,"Tournoi Touch Rugby mixte","Réinvestir continuité, largeur et replacement dans un tournoi organisé par les étudiants.",["RUG1","RUG2","RUG4"],
 ["Organisation des équipes et du tournoi.","Arbitrage et coaching étudiants.","Bilan collectif et rôles sociaux."]),
(7,"Projet de jeu offensif + PPI – Synthétique Escudé","Organiser l'attaque sur plusieurs temps de jeu.",["RUG1","RUG2","RUG4"],
 ["Fixation, intervalle, soutien axial et latéral.","Conservation après contact ; PPI spécifique rugby.","Opposition progressive."]),
(8,"Projet de jeu défensif / techniques de plaquage","Construire une défense collective et sécuriser le plaquage.",["RUG3","RUG4"],
 ["Ligne défensive, montée collective, communication, cadrage.","Plaquage sécurisé : tête, épaule, ceinture des bras, accompagnement au sol.","Replacement après intervention."]),
(9,"Mise en place / opposition raisonnée","Réviser les projets offensif et défensif en opposition contrôlée.",["RUG1","RUG2","RUG3","RUG4"],
 ["Révision des projets offensif/défensif et lancements de jeu.","Phases de conquête simplifiées.","Opposition contrôlée avec arrêts pédagogiques et analyse collective."]),
(10,"Mise en place / opposition raisonnée","Stabiliser automatismes et transitions avant la demi-finale intercampus.",["RUG1","RUG2","RUG3","RUG4"],
 ["Transitions attaque/défense et séquences proches des conditions universitaires.","Coaching entre pairs.","Préparation spécifique à la demi-finale intercampus."]),
(11,"½ finales Championnat Intercampus","Mettre en œuvre le projet collectif en rencontre universitaire.",["RUG1","RUG2","RUG3","RUG4"],
 ["Échauffement autonome et rencontre universitaire.","Rôles : joueur, coach, remplaçant, observateur, arbitre, feuille de match.","Situation privilégiée d'évaluation."]),
(12,"Rugby Park","Développer cohésion, coopération, réactivité et investissement dans les rôles sociaux.",["RUG1","RUG2","RUG4"],
 ["Jeux, challenges, réactivité et prise d'information.","Matchs et situations variées.","Cohésion du groupe et rôles sociaux."]),
(13,"Jeu déployé / jeu au pied + soirée de fin de semestre","Développer largeur, jeu au pied et replacement des soutiens.",["RUG1","RUG2","RUG4"],
 ["Occupation de la largeur et transmissions longues.","Jeu au pied d'occupation, pression et récupération.","Opposition finale, bilan du semestre et soirée de fin de semestre."]),
]
for n,t,o,comps,sits in rug_sessions:
    CYCLE_SESSION_SEEDS.append(_s("Rugby",n,t,o,comps,sits,
        material=("Ballons","Plots","Chasubles","Boucliers selon séance"),
        warmup="15-20 min : course, mobilité, manipulation du ballon et préparation spécifique.",
        criteria=["Réinvestir les apprentissages en situation de jeu."], safety=rug_safe,
        bilan="5-10 min : analyse des réussites, difficultés et objectifs de progression."))

# ---------------------------------------------------------------------------
# SSA — 22 séances
# ---------------------------------------------------------------------------
ssa_safe = ("Priorité à la sécurité et au contrôle technique.", "Aucune hyperventilation lors des exercices d'apnée.")
ssa = [
(1,"Diagnostic aquatique et découverte du SSA","Présenter le cadre SSA, évaluer le niveau initial et créer une fiche individuelle.",["SSA1","SSA5"],
 ["Présentation missions/sécurité/progression/TSA.","Échauffement 400-500 m ; diagnostic nage ; immersion ; mannequin ; mini-enchaînement."]),
(2,"Apnée, canard et récupération du mannequin","Améliorer l'immersion, maîtriser le canard et réduire les temps morts.",["SSA5"],
 ["400 m varié ; 6×10 m + 4×15 m immersion contrôlée.","Canard, prise d'objet, orientation ; 6-8 récupérations mannequin.","Enchaînement immersion + nage + canard + mannequin."]),
(3,"Nage d'approche et remorquage","Développer une approche efficace tête hors de l'eau et améliorer le remorquage.",["SSA5"],
 ["500 m ; 8×25 m tête haute.","8×25 m remorquage puis circuit 25 m crawl +15 m approche + mannequin +25 m remorquage."]),
(4,"Victime consciente et techniques de dégagement","Approcher une victime consciente en sécurité et gérer panique/saisies.",["SSA5"],
 ["Nage d'approche avec observation permanente.","Prise de contact, communication, sécurisation et maintien.","Dégagements progressifs puis cas concrets courts."]),
(5,"Construction du parcours TSA","Mémoriser l'enchaînement complet du TSA et identifier les transitions à optimiser.",["SSA5"],
 ["Bloc plongeon +15 m apnée + nage ; 4×50 crawl.","Second passage immersion ; approche tête haute, canard, mannequin, remorquage.","Parcours fractionné complet."]),
(6,"PRISE DE TEMPS N°1 - TSA diagnostic","Obtenir un premier temps de référence et constituer des groupes de besoin.",["SSA5"],
 ["Échauffement ciblé.","TSA chronométré : 1 passage par candidat.","Ateliers différenciés immersion/vitesse/mannequin/remorquage ; mini-TSA 70-80 %."]),
(7,"Palmes et préparation du 300 m","Optimiser chaussage/départ, palmage et allure spécifique 300 m.",["SSA5"],
 ["400 m sans palmes ; 8-10 chaussages/départs.","8×25 +4×50 technique ; 6×50 allure 300 m ; 2×150 m ; 100 m rapide."]),
(8,"Bouée tube et sauvetage avec matériel","Maîtriser la bouée tube, sécuriser une victime et remorquer efficacement.",["SSA5"],
 ["Prise en main : sangle, transport, entrée dans l'eau.","Approche et présentation à victime consciente ; 6×25 remorquage.","Relais sauvetage et cas concret victime consciente."]),
(9,"Sorties d'eau et extraction","Choisir une sortie adaptée et coordonner une extraction.",["SSA5"],
 ["Approche du bord et maintien de la victime.","Sortie par échelle ; dégagement d'urgence ; extraction à plusieurs.","Mini-cas victime inerte → récupération → extraction → relais secourisme."]),
(10,"PRISE DE TEMPS N°2 - TSA + 300 m palmes","Mesurer la progression et ajuster l'entraînement individuel.",["SSA5"],
 ["TSA chronométré.","Récupération minimum réglementaire.","300 m palmes chronométré puis bilan comparé à S6."]),
(11,"Victime traumatisée - suspicion de rachis","Identifier une situation traumatique et coordonner stabilisation/déplacement/extraction.",["SSA2","SSA5"],
 ["Analyse plongeon/choc/collision.","Stabilisation dans l'eau en binômes/trinômes ; déplacement coordonné.","Extraction sécurisée et cas concret faible profondeur."]),
(12,"Surveillance d'un établissement de baignade","Passer de nageur-sauveteur à surveillant, choisir son placement et détecter les signes de noyade.",["SSA1","SSA2","SSA3","SSA4"],
 ["Théorie active : rôle, zones, risques, prévention.","Placement et balayage visuel ; détection de scènes courtes.","Mise en situation surveillant + usagers + victime + équipier."]),
(13,"Prévention et analyse des risques","Analyser l'environnement, identifier les risques et proposer des mesures préventives.",["SSA2","SSA3","SSA4"],
 ["Visite active : profondeurs, accès, plages, matériel, alerte, zones à risque.","Cartographie des risques ; hygiène/qualité de l'eau ; risques particuliers.","Mise en situation prise de poste + restitution de 3 mesures préventives."]),
(14,"PRISE DE TEMPS N°3 + remédiation","Stabiliser le TSA, corriger les défauts individuels et développer la régularité.",["SSA5"],
 ["TSA chronométré ; récupération/analyse.","Ateliers individualisés départ/apnée/crawl/canard/mannequin/remorquage.","Deuxième tentative ciblée ou travail fractionné."]),
(15,"Cas concrets de surveillance","Développer détection, décision, communication et coordination prévention/intervention.",["SSA2","SSA3","SSA4","SSA5"],
 ["Scénarios : enfant perdu, nageur en difficulté progressive, victime silencieuse, comportement dangereux.","Reprise des situations insuffisamment maîtrisées ; synthèse collective."]),
(16,"Cas concrets de sauvetage","Réaliser une intervention complète adaptée au type de victime.",["SSA1","SSA5"],
 ["Cas victime consciente, paniquée, immergée, extraction.","Scénario surprise.","Débriefing collectif et transmissions."]),
(17,"Rôle, responsabilités et communication professionnelle","Situer prérogatives/limites, comprendre l'organisation des secours et communiquer.",["SSA1","SSA3","SSA4","SSA5"],
 ["Rôle du SSA ; responsabilités ; organisation des secours.","Jeux de rôle avec usagers ; traçabilité main courante/compte rendu.","Incident + intervention + compte rendu oral/écrit."]),
(18,"PRISE DE TEMPS N°4 - simulation certificative","Réaliser un TSA proche des conditions de certification et cibler la dernière remédiation.",["SSA5"],
 ["Échauffement libre guidé ; TSA chronométré.","300 m palmes chronométré après récupération.","Bilan individuel et objectif final."]),
(19,"Simulation professionnelle - évaluation formative","Mobiliser et évaluer les cinq compétences du référentiel dans une même situation.",["SSA1","SSA2","SSA3","SSA4","SSA5"],
 ["Prévention d'un comportement dangereux ; victime en difficulté ; victime immergée ; accident traumatique.","Reprise d'une situation imposée et entretien pédagogique."]),
(20,"Cas complexes et action coordonnée","Gérer une situation dégradée, coopérer et maintenir la surveillance du public.",["SSA2","SSA3","SSA4","SSA5"],
 ["Forte fréquentation + comportements à risque ; victime non visible ; bouée tube.","Victime traumatisée à plusieurs ; évacuation partielle du bassin.","Débriefing coordination/communication."]),
(21,"PRISE DE TEMPS N°5 - TSA blanc","Répéter les conditions réelles et vérifier les seuils certificatifs.",["SSA5"],
 ["Échauffement individualisé ; TSA blanc.","Récupération minimum 10 min ; 300 m nage libre avec palmes.","Bilan individuel/remédiation éventuelle."]),
(22,"Évaluation finale, certification et bilan","Valider les compétences restantes et formaliser le bilan individuel.",["SSA1","SSA2","SSA3","SSA4","SSA5"],
 ["Validation des épreuves restant à acquérir selon le référentiel interne.","Situations professionnelles sommatives : prévention, surveillance, sauvetage, coordination.","Entretien individuel et bilan du cycle."]),
]
for n,t,o,comps,sits in ssa:
    CYCLE_SESSION_SEEDS.append(_s("Sauvetage",n,t,o,comps,sits,
        material=("Matériel SSA adapté à la séance","Chronomètres et fiches de suivi si nécessaire"),
        warmup="Échauffement adapté au thème de séance.",
        criteria=["Respecter les critères techniques, de sécurité et d'autonomie du document pédagogique."],
        safety=ssa_safe,
        bilan="Débriefing et traçabilité sur la fiche individuelle de suivi."))


assert len(CYCLE_SESSION_SEEDS) == 53
